name: test

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v3

    - uses: gacts/run-and-post-run@v1
      id: post-run-command
      with:
        post: |
          echo "::group::Step results"
          echo "one=${{ steps.one.outcome }}"
          echo "two=${{ steps.two.outcome }}"
          echo "three=${{ steps.three.outcome }}"
          echo "::endgroup::"
          if [ ${{ steps.one.outcome == 'failure' || \
                   steps.two.outcome == 'failure' || \
                   steps.three.outcome == 'failure' }} ]; then \
            echo "::error::One or more steps failed"; \
            exit 1; \
          fi

    - id: one
      #if: ${{ 1 == 2 }}
      continue-on-error: true
      run: exit 1
    - id: two
      continue-on-error: true
      run: exit 0
    - id: three
      continue-on-error: true
      run: exit 0
