name: test

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v3

    - uses: gacts/run-and-post-run@v1
      id: post-run-command
      with:
        post: |
          if [ ${{ steps.one.outcome == 'failure' || steps.two.outcome == 'failure' || steps.three.outcome == 'failure' }} ]; then \
            echo "failed"; \
          fi

    - uses: webiny/action-post-run@3.0.0
      id: check-for-failures
      with:
        run: |
          if [ ${{ steps.one.outcome == 'failure' || steps.two.outcome == 'failure' || steps.three.outcome == 'failure' }} ]; then \
            echo "failed"; \
          fi

    - id: one
      #if: ${{ 1 == 2 }}
      continue-on-error: true
      run: exit 1
    - id: two
      continue-on-error: true
      run: exit 0
    - id: three
      continue-on-error: true
      run: exit 0
