name: test

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v3

    - uses: gacts/run-and-post-run@v1
      id: post-run-command
      if: |
        steps.one.outcome == 'failure' ||
        steps.two.outcome != 'success' ||
        steps.three.outcome != 'success'
      with:
        post: |
          FAIL=(${{ steps.one.outcome == 'failure' || steps.two.outcome == 'failure' || steps.three.outcome == 'failure' }})
          echo "::notice::one=${{ steps.one.outcome }}"
          echo "::notice::two=${{ steps.two.outcome }}"
          echo "::notice::three=${{ steps.three.outcome }}"
          [[ $FAIL ]] && echo "::error::One or more steps failed" && exit 1

    - id: one
      if: ${{ 1 == 2 }}
      continue-on-error: true
      run: exit 1
    - id: two
      continue-on-error: true
      run: exit 0
    - id: three
      continue-on-error: true
      run: exit 0

