name: test

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v3

    - uses: gacts/run-and-post-run@v1
      id: post-run-command
      if: |
        steps.one.outcome == 'failure' ||
        steps.two.outcome != 'success' ||
        steps.three.outcome != 'success'
      with:
        #env:
        #  STEPS_FAIL: "${{ (steps.one.outcome == 'failure' || steps.two.outcome == 'failure' || steps.three.outcome == 'failure') }}"
        #  STEPS_PASS: "${{ (steps.one.outcome == 'success' || steps.one.outcome == 'skipped') }}"
        post-shell: bash -e
        post: |
          echo "start"
          #echo "::group::Step results"
          #echo "one=${{ steps.one.outcome }}"
          #echo "two=${{ steps.two.outcome }}"
          #echo "three=${{ steps.three.outcome }}"
          #echo "::endgroup::"
          X="true"
          Y="false"
          XB=true
          YB=false
          echo $X
          echo $XB
          echo $Y
          echo $YB
          echo "finish"

    - id: one
      #if: ${{ 1 == 2 }}
      continue-on-error: true
      run: exit 1
    - id: two
      continue-on-error: true
      run: exit 0
    - id: three
      continue-on-error: true
      run: exit 0
    - id: four
      run: |
        echo "start"
        X="true"
        Y="false"
        XB=true
        YB=false
        echo $X
        echo $XB
        echo $Y
        echo $YB
        echo "finish"
